# SPDX-FileCopyrightText: 2024 Brian Kubisiak <brian@kubisiak.com>
#
# SPDX-License-Identifier: GPL-3.0-only

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "scripts"
version = "0"
authors = [
    { name = "Brian Kubisiak", email = "brian@kubisiak.com" },
]
description = "Misc scripts for uncommon tasks"
dependencies = [
    "defusedxml == 0.7.*",
    "garmin-fit-sdk == 21.*",
    "pillow == 11.*",
    "rich == 13.*",
]

[project.scripts]
garmin-xero = "garmin_xero:main"
solarize = "solarize:main"
mdd-to-org = "mdd_to_org:main"

[tool.black]
line-length = 79

[tool.mypy]
disallow_untyped_defs = true

[tool.setuptools]
py-modules = ["garmin_xero", "mdd_to_org", "solarize"]